version: "3.9"
services:
  web:
    build: .
    command: python source/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
    env_file: source/.env


