version: "3.9"
services:
  database:
    image: postgres:14.2-alpine
    env_file: .env-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: python source/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: on-failure
    env_file: source/.env

volumes:
  db-data: