# Generated by Django 4.1.3 on 2022-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rank', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('artist', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('chart', models.CharField(max_length=15)),
                ('streams', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
