# Generated by Django 4.1.3 on 2022-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifydata',
            name='date',
            field=models.DateField(),
        ),
    ]
