# Generated by Django 4.1.3 on 2023-01-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_data.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('streams', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='re_artist', to='spotify_data.artisttitle')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_data.chart')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_data.rank')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_data.region')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='re_title', to='spotify_data.artisttitle')),
            ],
        ),
        migrations.AddField(
            model_name='artisttitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_data.title'),
        ),
    ]
